### ISSUE TITLE
Math latex expression within a diagram

### ISSUE THREAD

**Issue by ipocentro87** [reelsense/markdeep#3]
Hi reelsense,
I would like to ask you whether it is possible to write a mathematical expression within a diagram in markdeep. It would be very useful for me.

Example:

```
********************************
*
* .-----.
* |     |  $a_i$
* '-----'
*
********************************
```

**Comment by reelsense** [comment]
Unfortunately I have know idea. 

I made this mirror of markdeep back when markdeep only existed on Morgan's website and it didn't have any public version control. I would just manually copy the state of it into GitHub to store working versions for my self. Now I continue to cryptographically sign and maintain a parallel construction to scratch my own itch. I use markdeep in _everything_ I work on now...

I suggest contacting the guru him self, @morgan3d at morgan@casual-effects.com or checking his FAQ: http://casual-effects.com/markdeep/

---
If @morgan3d sees this, I suggest re-enabling GH Issues on your repo. Also thank you very much for _markdeep_, you would be surprised how much support you would get if you added a **Donate** button to your site. 😄

**Comment by morgan3d** [comment]
Just send me an email with any change that you'd like merged. I disabled
pull requests and issues because I keep the Markdeep source in a different
system alongside all of my other projects and only push to git to publish
it.

-m


Prof. Morgan McGuire
Computer Science Department
Williams College
http://cs.williams.edu/~morgan
